### ISSUE TITLE
希望歌曲列表中可以加上是否喜欢的那个图标

### ISSUE THREAD

**Issue by logxing** [chen310/plugin.audio.music163#15]
希望歌曲列表中可以加上是否喜欢的那个图标，即PC版中那个红心和空心。歌曲的悬浮菜单中也标识是否喜欢。（喜欢实际上是加入用户的一个特殊的歌单：username喜欢的音乐）

希望歌单列表中可以加上图标来明示该歌单是否已经收藏，或者至少在光标移动到该歌单时，左侧的歌单详细信息中可以标识该歌单是否已经收藏。歌单的悬浮菜单中标识是否已收藏。目前是一直显示收藏，如果收藏过再次点击收藏才会提示收藏失败。

以上需求的原因：我一般每天是打开私人雷达，听听那些还没有被我加入“我喜欢的音乐”歌单的音乐，也就是PC上显示空心的那些歌曲，把好听的标识喜欢。再就是浏览推荐歌单中尚未收藏的歌单。因此我的需求是对歌曲是否已经标识为喜欢，和歌单是否已经收藏做到一目了然。

再次感谢作者，终于可以在电视上放网易云音乐了。

**Comment by chen310** [comment]
已添加红心标志，到 Actions 中下载

**Comment by chen310** [comment]
推荐歌单接口返回的数据中没有是否已收藏这一项，所以没法直接显示是否已收藏
