### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by lancerwhite** [chen310/plugin.audio.music163#21]
网易云pc版恢复杜比全景声的时候，希望大大新增杜比全景声的音质选项。另外感谢大大，插件很好用！！

**Comment by chen310** [comment]
开启或关闭杜比全景声，返回的音频文件好像都是一样的

**Comment by chen310** [comment]
@lancerwhite 可能是我没生效，杜比是不是SVIP才能使用？

**Comment by lancerwhite** [comment]
@chen310

**Comment by chen310** [comment]
@lancerwhite 没有SVIP账号可以测试

**Comment by lancerwhite** [comment]
@chen310 加小飞机我借给你？

**Comment by chen310** [comment]
@lancerwhite 如何联系

**Comment by lancerwhite** [comment]
@chen310 加我QQ1569314963

**Comment by lancerwhite** [comment]
@chen310 打错了……是1563914963
