### ISSUE TITLE
[Bug] 手动切换歌曲时，播放页不显示专辑封面

### ISSUE THREAD

**Issue by FrzMtrsprt** [chen310/plugin.audio.music163#3]
如题，手动从列表选择歌曲，或在播放页点击上一曲/下一曲时，播放页不显示专辑封面；但自动切换歌曲（播放完当前歌曲后，自动重复播放/播放下一首）时，专辑封面显示正常。

**Comment by chen310** [comment]
已知问题，暂时没法解决

**Comment by chen310** [comment]
这个问题是从 Kodi 19 开始有的，Kodi 18 没有这个问题。不行的话，就先用 Kodi 18
